language: objective-c
os: osx
osx_image: xcode9
xcode_project: iOS Travis Test.xcodeproj
xcode_scheme: iOS Travis Test
before_script:
- security create-keychain -p travis ios-build.keychain
- security import ./certs/apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import ./certs/dist.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import ./certs/dist.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD
  -T /usr/bin/codesign
script:
- xcodebuild clean test -project 'iOS Travis Test.xcodeproj' -scheme "iOS Travis Test"
  -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' CODE_SIGNING_REQUIRED=NO
  CODE_SIGN_IDENTITY=""
after_script:
- security delete-keychain ios-build.keychain
after_success:
- echo "Configure Travis CI to deploy into TestFlight"
env:
  global:
    secure: FFtpiLKp9KkiyIb+zJCnlE55EtTojTQeeMh/2d8fDml2/+xNtU24ieTDFp2j4Mj7In8RC7snelm++dB1UheutqVQ298DTkyUxgV43i7jE0Wp6Yv+7GXlvGsPQbuAHXx4v9gRhxIWthav5hYAwlj4tlee/+y5RvEjxJudtAFIlEuz8LWguEo3taeOVlEXqHfeJcTzeiPLbdmNb4MD8tLMD7FBK5P/d09wh4R+Z5n15zBg2GqAAVFRVZdhqG4mnRQlATv4ihitr9WbcthNDwb9W5uns62tRuSkIBweDekr0kKxFjWXTSqtkELEkvah6B+tiwoZZxVVxNbqFVLh/mBBDvKc2gbDrzN5lP6AbP2dbPg9lIs4r//FH182mrmdSArdkkGoR+ucG5WLP6pm8PYhPjRpTcpYQw3kqc9cLx6JqvvTbSlfY3C0jTLq5dsDUWkHxAWq8Uu1nqF2PynFUuxGxZ6D7MK/T7A88acM7SN4TNtTnoMWYPkeZPIBmwwJNlOL08Tmo6aO5NIftpZhpDY+XnTo0afDLF1ITTFy/8G1d5cXahIX6sM6ewGflqQIjPDJPC6dq8QAzKNNUnfMzPxa02t6tAaCTA1kLzj2comUIiPHCydVl2A4eLi8J90gzm3N6jkvVYzrwmah8hT+4hH8YVkIe0Xoe7c5YsszXFN+Kj0=
