language: objective-c
os: osx
osx_image: xcode9
xcode_project: iOS Travis Test.xcodeproj
xcode_scheme: iOS Travis Test
before_script:
- security create-keychain -p travis ios-build.keychain
- security import ./certs/apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import ./certs/dist.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import ./certs/dist.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD
  -T /usr/bin/codesign
script:
- xcodebuild clean test -project 'iOS Travis Test.xcodeproj' -scheme "iOS Travis Test"
  -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.0' CODE_SIGNING_REQUIRED=NO
  CODE_SIGN_IDENTITY=""
after_script:
- security delete-keychain ios-build.keychain
after_success:
- echo "Configure Travis CI to deploy into TestFlight"
env:
  global:
    secure: cjWTWJQLtTdQIMda59ayRH2Kz6tBMytjPcJ3hMxgyqyPQygJ7X+5ky6jnXeIwrQ7e7WgZh9k3w+G6zYE+5nfh8cIAP1vk4tUibhHMnwCYSqGIQi89uSw5ztOXo12bylpzhAJI6SE2wA3waqaqaWZYfCw3/SyIB8pYfVrrAwtsbdLolvbs4lV9hZSD9e/TN0xaOvjOGn3M1XyyOBdqQeY2Ano+oG9GXZz/lM1ZS4Z/BchvLy7pcr5KSAJT/7/RlNGtEfPblXe+9rMMwcsMKdfqhpcshEBwQfzk2LhZQdBsjidAv8MJQpPlaaUCVdZKUFM5ybD+TB73NjNzIxM4ZRejF+hxuwgjzzEVso9WYwTQHZEiwphpNDz1E9xFBixuEEMy8wQbQzlAvPzA4MZ2AKwQOTnIhynEG+sZqxkY7Su4hUZEirKzCDwuFQ8KVR6S6V1HmN25ClFxqm0+/DCAJ2BIUwXlPgGA/2sPszM6i6OuQJ8KAzrZfy4QpNr8+mUXkaRyeqZzAqVG9h+tj9UremTbV4xmBxHuAk3/DqiDVggROGqOcGzCroSYrYL47Wze5zm/wJCzsG+wkaT/5JhyS5wZo+tBuZz+7nL5Jld4u5l+22iUO8tUsZadT3k7NAXJQnLkTp3GLvKwVQTIiWK1bQ1eGNs82xd13njeazD4I6M7Cg=
